name: Build Custom Debian Live ISO

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: 'Enable tmate debugging session'
        required: false
        default: false

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: debian:sid
      options: --privileged
    timeout-minutes: 120

    steps:
      - name: Install git and essential packages
        run: |
          apt-get update
          apt-get install -y git curl ca-certificates

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Fix ownership warning
        run: git config --global --add safe.directory /__w/live-build/live-build
  
      - name: Create Build Directory
        run: mkdir -p /__w/live-build/live-build/build

      - name: Configure build environment
        id: config
        run: |
          echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
          echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
          echo "BUILD_DIR=${{ github.workspace }}/build" >> $GITHUB_ENV
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $2}')
          echo "ISO_NAME=${REPO_NAME}-live-$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Install live-build and dependencies
        run: |
          apt-get install -y \
            live-build \
            xorriso \
            isolinux \
            syslinux-common \
            debootstrap \
            squashfs-tools \
            wget \
            jq \
            mmdebstrap \
            apt-utils \
            dpkg-dev \
            debian-archive-keyring \
            debian-keyring

      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}
        with:
          limit-access-to-actor: true

      - name: Validate live-build configuration
        id: validate
        run: |
          if [ ! -d "auto" ]; then
            echo "::warning::No auto/ directory found, using default configuration"
            mkdir -p auto
            cat > auto/config << 'EOF'
          #!/bin/sh
          set -e
          lb config noauto \
            --distribution sid \
            --architectures amd64 \
            --binary-images iso-hybrid \
            --debian-installer live \
            --debian-installer-gui true \
            --archive-areas "main contrib non-free non-free-firmware" \
            --apt-indices false \
            --security true \
            --source false \
            --bootappend-live "boot=live components locales=en_US.UTF-8" \
            "${@}"
          EOF
            chmod +x auto/config
          fi
          
          if [ ! -d "config/package-lists" ]; then
            echo "::warning::No package lists found, creating minimal package list"
            mkdir -p config/package-lists
            echo "task-xfce-desktop" > config/package-lists/desktop.list.chroot
            echo "linux-image-amd64" > config/package-lists/kernel.list.chroot
            echo "firmware-linux" >> config/package-lists/kernel.list.chroot
          fi
          
          if [ -f "auto/config" ] && [ ! -x "auto/config" ]; then
            chmod +x auto/config
          fi

      - name: Clean build environment
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          if command -v lb &> /dev/null; then
            lb clean --purge
          fi

      - name: Initialize live-build configuration
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          cp -r ${{ github.workspace }}/auto ${{ env.BUILD_DIR }}/ || true
          mkdir -p ${{ env.BUILD_DIR }}/config
          cp -r ${{ github.workspace }}/config/* ${{ env.BUILD_DIR }}/config/ || true
          
          if [ -f "auto/config" ]; then
            ./auto/config
          else
            echo "::error::Could not find auto/config after preparation"
            exit 1
          fi

      - name: Build live system ISO
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          cat > build.sh << 'EOF'
          #!/bin/bash
          set -eo pipefail
          
          exec > >(tee -a build.log) 2>&1
          
          echo "Starting live-build process at $(date)"
          
          if [ -f "auto/build" ]; then
            ./auto/build
          else
            lb build
          fi
          
          if ls live-image-*.iso 1> /dev/null 2>&1; then
            echo "ISO build successful!"
            for iso in live-image-*.iso; do
              mv "$iso" "../${{ env.ISO_NAME }}.iso"
              echo "::set-output name=iso_path::${{ env.BUILD_DIR }}/../${{ env.ISO_NAME }}.iso"
              echo "::set-output name=iso_name::${{ env.ISO_NAME }}.iso"
              break
            done
          else
            echo "::error::ISO build failed! No ISO file found."
            exit 1
          fi
          EOF
          
          chmod +x build.sh
          timeout 90m ./build.sh || {
            echo "::error::Build failed or timed out after 90 minutes"
            if [ -f "build.log" ]; then
              cp build.log ${{ github.workspace }}/build.log
            fi
            exit 1
          }

      - name: Generate checksums
        run: |
          ISO_PATH="${{ env.BUILD_DIR }}/../${{ env.ISO_NAME }}.iso"
          if [ -f "$ISO_PATH" ]; then
            cd $(dirname "$ISO_PATH")
            sha256sum "${{ env.ISO_NAME }}.iso" > "${{ env.ISO_NAME }}.sha256sum"
            echo "::notice::ISO checksum generated successfully"
          else
            echo "::error::ISO file not found at expected location"
            exit 1
          fi

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs
          path: |
            ${{ env.BUILD_DIR }}/build.log
            ${{ env.BUILD_DIR }}/chroot.packages.live
            ${{ env.BUILD_DIR }}/.build/
          retention-days: 7

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ISO_NAME }}
          path: |
            ${{ env.BUILD_DIR }}/../${{ env.ISO_NAME }}.iso
            ${{ env.BUILD_DIR }}/../${{ env.ISO_NAME }}.sha256sum
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.BUILD_DIR }}/../${{ env.ISO_NAME }}.iso
            ${{ env.BUILD_DIR }}/../${{ env.ISO_NAME }}.sha256sum
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}